version: 4
x-podman:
  use-pod: false
services:
  nginx:
    image: docker.io/nginx:1-alpine
  router:
    image: quay.io/skupper/skupper-router:main
    environment:
      QDROUTERD_CONF: /etc/skupper-router/config/skrouterd.json
      QDROUTERD_CONF_TYPE: json
      SKUPPER_SITE_ID: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
    volumes: ./config:/etc/skupper-router/config:ro,z
    ports:
      - 8180:8180
  collector:
    image: quay.io/skupper/network-console-collector:v2-latest
    command:
      - -router-endpoint=amqp://router:5672
      - -prometheus-api=http://prometheus:9090
      - -flow-record-ttl=1m
    ports:
      - 8080:8080
  prometheus:
    image: docker.io/prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus:ro,z
      - prom_data:/prometheus
  podman-exporter:
    image: quay.io/navidys/prometheus-podman-exporter
    userns_mode: keep-id
    environment:
      - CONTAINER_HOST=unix:///run/podman/podman.sock 
    security_opt:
      - "label=disable"
    volumes:
      - "$XDG_RUNTIME_DIR/podman/podman.sock:/run/podman/podman.sock"
  grafana:
    image: docker.io/grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro,z
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro,z
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro,z
volumes:
  prom_data:
