version: 4
services:
  router-01:
    image: quay.io/skupper/skupper-router:main
    environment:
      QDROUTERD_CONF: /etc/skupper-router/config/skrouterd.json
      QDROUTERD_CONF_TYPE: json
      SKUPPER_SITE_ID: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1
    volumes:
      - ./config/01:/etc/skupper-router/config:ro,z
    ports:
      - 15671:5672
  router-02:
    image: quay.io/skupper/skupper-router:main
    environment:
      QDROUTERD_CONF: /etc/skupper-router/config/skrouterd.json
      QDROUTERD_CONF_TYPE: json
      SKUPPER_SITE_ID: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2
    volumes:
      - ./config/02:/etc/skupper-router/config:ro,z
    ports:
      - 15672:5672
  router-03:
    image: quay.io/skupper/skupper-router:main
    environment:
      QDROUTERD_CONF: /etc/skupper-router/config/skrouterd.json
      QDROUTERD_CONF_TYPE: json
      SKUPPER_SITE_ID: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3
    volumes:
      - ./config/03:/etc/skupper-router/config:ro,z
    ports:
      - 15673:5672
