{
 "title": "Vanflow Collector Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Service",
    "label": "service",
    "query": {
     "query": "label_values(skupper_sent_bytes_total, routing_key)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Traffic by Process (Bytes per Second)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (source_process_name, dest_process_name) (rate(skupper_sent_bytes_total{routing_key=\"$Service\"}[1m]) + rate(skupper_received_bytes_total{routing_key=\"$Service\"}[1m]))",
     "legendFormat": "{{source_process_name}} to {{dest_process_name}}"
    }
   ]
  },
  {
   "title": "Open Connections By Process",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source_process_name, dest_process_name) (skupper_connections_opened_total{routing_key=\"$Service\"} - skupper_connections_closed_total{routing_key=\"$Service\"})",
     "legendFormat": "{{source_process_name}} to {{dest_process_name}}"
    }
   ]
  },
  {
   "title": "Service Traffic by Site (Bytes per Second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (source_site_name, dest_site_name) (rate(skupper_sent_bytes_total{routing_key=\"$Service\"}[1m]) + rate(skupper_received_bytes_total{routing_key=\"$Service\"}[1m]))",
     "legendFormat": "{{source_site_name}} to {{dest_site_name}}"
    }
   ]
  },
  {
   "title": "Open Connections By Site",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 11, "y": 13 },
   "targets": [
    {
     "expr": "sum by (source_site_name, dest_site_name) (skupper_connections_opened_total{routing_key=\"$Service\"} - skupper_connections_closed_total{routing_key=\"$Service\"})",
     "legendFormat": "{{source_site_name}} to {{dest_site_name}}"
    }
   ]
  },
  {
   "title": "2xx HTTP Requests by Processes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (source_process_name, dest_process_name) (rate(skupper_requests_total{routing_key=\"$Service\", code=\"2xx\"}[1m]))",
     "legendFormat": "2xx {{source_process_name}} to {{ dest_process_name}}"
    }
   ]
  },
  {
   "title": "Non-2xx HTTP Requests by Processes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (source_process_name, dest_process_name, code) (rate(skupper_requests_total{routing_key=\"$Service\", code!=\"2xx\"}[1m]))",
     "legendFormat": "{{code}} {{source_process_name}} to {{ dest_process_name}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg by (source_process, dest_process) (skupper_internal_latency_seconds_sum{routing_key=\"$Service\"}/skupper_internal_latency_seconds_count{routing_key=\"$Service\"})"
      }
     ]
    },
    {
     "title": "TTFB",
     "type": "graph",
     "gridPos": { "h": 10, "w": 9, "x": 9, "y": 2 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "legacy_flow_latency_microseconds_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collector Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"ck-a\", pod=~\"network-console-.*\"})"
    }
   ]
  },
  {
   "title": "Collector CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"ck-a\", pod=~\"network-console-collector-.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Flows Record Updates (per second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(skupper_internal_flow_processing_seconds_count[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Open Connections",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(skupper_connections_opened_total - skupper_connections_closed_total)"
    }
   ]
  },
  {
   "title": "Flow Record Processing Time (per second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(skupper_internal_flow_processing_seconds_sum[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Flow Record Processing Queue Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (type) (skupper_internal_queue_utilization_percentage)"
    }
   ]
  },
  {
   "title": "Collector Reconcile Processing Time (per second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(skupper_internal_collector_job_seconds_sum[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Pending Flows",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type, reason) (skupper_internal_pending_flows)",
     "legendFormat": "{{type}} {{reason}}"
    }
   ]
  }
 ]
}